const OK_STATUS = 200;

const CREATED_STATUS = 201;

const BAD_REQUEST_ERROR = 400;

const UNAUTHORIZED_ERROR = 401;

const FORBIDDEN_ERROR = 403;

const NOT_FOUND_ERROR = 404;

const CONFLICT_ERROR = 409;

const SERVER_ERROR = 500;

module.exports = {
  BAD_REQUEST_ERROR,
  NOT_FOUND_ERROR,
  SERVER_ERROR,
  UNAUTHORIZED_ERROR,
  OK_STATUS,
  CREATED_STATUS,
  FORBIDDEN_ERROR,
  CONFLICT_ERROR,
};
